from sql import query, table

import os
from dotenv import load_dotenv
load_dotenv() 


DATABASES = {
    'JJsNBA':{
        'server': os.getenv('ServerIP'),
        'database': 'JJsNBA', #os.getenv('Database'),
        'username': 'jjAdmin',
        'password': os.getenv('AdminPass')
    }
}

TABLES = {

#region schema: dbo
    'Team':{
        'keys': ['SeasonID', 'TeamID',],
        'columns': ['SeasonID',
            'TeamID',
            'City',
            'Name',
            'Tricode',
            'Wins',
            'Losses',
            'FullName',
            'Conference',
            'Division'
        ],
        'update_columns': ['Wins', 'Losses'],
        'create': table(name='Team')
    },
    'Arena':{
        'keys': ['SeasonID', 'ArenaID'],
        'columns': [
            'SeasonID',
            'ArenaID',
            'TeamID',
            'City',
            'Country',
            'Name',
            'PostalCode',
            'State',
            'StreetAddress',
            'Timezone'
        ],
        'update_columns': [],
        'create': table(name='Arena')
    },
    'Official':{
        'keys': ['SeasonID', 'OfficialID'],
        'columns': [
            'SeasonID',
            'OfficialID',
            'Name',
            'Number'
        ],
        'update_columns': [],
        'create': table(name='Official')
    },
    'Player':{
        'keys': ['SeasonID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'PlayerID',
            'Name',
            'Number',
            'Position',
            'NameInitial',
            'NameLast',
            'NameFirst'
        ],
        'update_columns': [],
        'create': table(name='Player')
    },
    'Game':{
        'keys': ['SeasonID', 'GameID'],
        'columns':[
            'SeasonID',
            'GameID',
            'Date',
            'GameType',
            'HomeID',
            'HScore',
            'AwayID',
            'AScore',
            'WinnerID',
            'WScore',
            'LoserID',
            'LScore',
            'SeriesID',
            'Datetime',
        ],
        'update_columns':[
            'HScore', 
            'AScore', 
            'WinnerID', 
            'WScore', 
            'LoserID', 
            'LScore'
        ],
        'create': table(name='Game')
    },
    'GameExt':{
        'keys': ['SeasonID', 'GameID'],
        'columns':[
            'SeasonID',
            'GameID',
            'ArenaID', 
            'Attendance', 
            'Sellout', 
            'Label', 
            'LabelDetail', 
            'OfficialID', 
            'Official2ID', 
            'Official3ID', 
            'OfficialAlternateID', 
            'Status', 
            'Periods'
        ],
        'update_columns':[
            'Attendance', 
            'Sellout', 
            'Label', 
            'LabelDetail', 
            'Status', 
            'Periods'
        ],
        'create': table(name='GameExt')
    },
    'TeamBox':{
        'keys':['SeasonID', 'GameID', 'TeamID', 'MatchupID'],
        'columns':[
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'Points',
            'PointsAgainst',
            'FG2M',
            'FG2A',
            '[FG2%]',
            'FG3M',
            'FG3A',
            '[FG3%]',
            'FGM',
            'FGA',
            '[FG%]',
            'FieldGoalsEffectiveAdjusted',
            'FTM',
            'FTA',
            '[FT%]',
            'SecondChanceFGM',
            'SecondChanceFGA',
            '[SecondChanceFG%]',
            'TrueShootingAttempts',
            'TrueShootingPercentage',
            'PtsFromTurnovers',
            'PtsSecondChance',
            'PtsInThePaint',
            'PaintFGM',
            'PaintFGA',
            '[PaintFG%]',
            'PtsFastBreak',
            'FastBreakFGM',
            'FastBreakFGA',
            '[FastBreakFG%]',
            'BenchPoints',
            'ReboundsDefensive',
            'ReboundsOffensive',
            'ReboundsPersonal',
            'ReboundsTeam',
            'ReboundsTeamDefensive',
            'ReboundsTeamOffensive',
            'ReboundsTotal',
            'Assists',
            'AssistsTurnoverRatio',
            'BiggestLead',
            'BiggestLeadScore',
            'BiggestScoringRun',
            'BiggestScoringRunScore',
            'TimeLeading',
            'TimesTied',
            'LeadChanges',
            'Steals',
            'Turnovers',
            'TurnoversTeam',
            'TurnoversTotal',
            'Blocks',
            'BlocksReceived',
            'FoulsDrawn',
            'FoulsOffensive',
            'FoulsPersonal',
            'FoulsTeam',
            'FoulsTeamTechnical',
            'FoulsTechnical',
            'Wins',
            'Losses',
            'Win',
            'Seed'
        ],
        'update_columns': [
            'Points',
            'PointsAgainst',
            'FG2M',
            'FG2A',
            '[FG2%]',
            'FG3M',
            'FG3A',
            '[FG3%]',
            'FGM',
            'FGA',
            '[FG%]',
            'FieldGoalsEffectiveAdjusted',
            'FTM',
            'FTA',
            '[FT%]',
            'SecondChanceFGM',
            'SecondChanceFGA', 
            '[SecondChanceFG%]',
            'TrueShootingAttempts',
            'TrueShootingPercentage',
            'PtsFromTurnovers',
            'PtsSecondChance',
            'PtsInThePaint',
            'PaintFGM',
            'PaintFGA',
            '[PaintFG%]',
            'PtsFastBreak',
            'FastBreakFGM',
            'FastBreakFGA',
            '[FastBreakFG%]',
            'BenchPoints',
            'ReboundsDefensive',
            'ReboundsOffensive',
            'ReboundsPersonal',
            'ReboundsTeam',
            'ReboundsTeamDefensive',
            'ReboundsTeamOffensive',
            'ReboundsTotal',
            'Assists',
            'AssistsTurnoverRatio',
            'BiggestLead',
            'BiggestLeadScore',
            'BiggestScoringRun',
            'BiggestScoringRunScore',
            'TimeLeading',
            'TimesTied',
            'LeadChanges',
            'Steals',
            'Turnovers',
            'TurnoversTeam',
            'TurnoversTotal',
            'Blocks',
            'BlocksReceived',
            'FoulsDrawn',
            'FoulsOffensive',
            'FoulsPersonal',
            'FoulsTeam',
            'FoulsTeamTechnical',
            'FoulsTechnical',
            'Wins', 
            'Losses',
            'Win',
            'Seed'
        ],
        'create': table(name='TeamBox')
    },
    'PlayerBox':{
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'Status',
            'Starter', 
            'Position', 
            'Minutes', 
            'MinutesCalculated', 
            'Points',
            'Assists',
            'ReboundsTotal',
            'FG2M',
            'FG2A',
            '[FG2%]',
            'FG3M', 
            'FG3A',
            '[FG3%]',
            'FGM', 
            'FGA', 
            '[FG%]', 
            'FTM', 
            'FTA', 
            '[FT%]', 
            'ReboundsDefensive', 
            'ReboundsOffensive', 
            'Blocks', 
            'BlocksReceived', 
            'Steals', 
            'Turnovers', 
            'AssistsTurnoverRatio', 
            'Plus', 
            'Minus', 
            'PlusMinusPoints',
            'PtsFastBreak',
            'PtsInThePaint',
            'PtsSecondChance', 
            'FoulsOffensive', 
            'FoulsDrawn', 
            'FoulsPersonal', 
            'FoulsTechnical', 
            'StatusReason', 
            'StatusDescription'

        ],
        'update_columns': [
            'Status',
            'Starter',
            'Position',
            'Minutes',
            'MinutesCalculated',
            'Points',
            'Assists',
            'ReboundsTotal',
            'FG2M',
            'FG2A',
            '[FG2%]',
            'FG3M',
            'FG3A',
            '[FG3%]',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'ReboundsDefensive',
            'ReboundsOffensive',
            'Blocks',
            'BlocksReceived',
            'Steals',
            'Turnovers',
            'AssistsTurnoverRatio',
            'Plus',
            'Minus',
            'PlusMinusPoints',
            'PtsFastBreak',
            'PtsInThePaint',
            'PtsSecondChance',
            'FoulsOffensive',
            'FoulsDrawn',
            'FoulsPersonal',
            'FoulsTechnical',
            'StatusReason',
            'StatusDescription'
        ],
        'create': table(name='PlayerBox')
    },    
    'StartingLineups':{
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'Unit',
            'Position'
        ],
        'update_columns': [],
        'create': table(name='StartingLineups')
    },
    'PlayByPlay':{
        'keys': [],
        'columns': [
            'SeasonID',
            'GameID',
            'ActionID',
            'ActionNumber',
            'Qtr',
            'Clock',
            'TimeActual',
            'ScoreHome',
            'ScoreAway',
            'Possession',
            'TeamID',
            'Tricode',
            'PlayerID',
            'Description',
            'SubType',
            'IsFieldGoal',
            'ShotResult',
            'ShotValue',
            'ActionType',
            'ShotDistance',
            'Xlegacy',
            'Ylegacy',
            'X',
            'Y',
            'Location',
            'Area',
            'AreaDetail',
            'Side',
            'ShotType',
            'PtsGenerated',
            'Descriptor',
            'Qual1',
            'Qual2',
            'Qual3',
            'ShotActionNbr',
            'PlayerIDAst',
            'PlayerIDBlk',
            'PlayerIDStl',
            'PlayerIDFoulDrawn',
            'PlayerIDJumpW',
            'PlayerIDJumpL',
            'OfficialID',
            'QtrType'
        ],
        'update_columns': [],
        'check_query': '''select count(p.ActionID) Actions
, max(ActionNumber) LastActionNumber
, s.Status
from PlayByPlay p
left join StintStatus s on p.SeasonID = s.SeasonID and p.GameID = s.GameID
where p.SeasonID = season_id and p.GameID = game_id
group by s.Status''',
        'create': table(name='PlayByPlay')
    },
    'StintStatus':{
        'keys': ['SeasonID', 'GameID'],
        'columns': [
            'SeasonID',
            'GameID'
        ],
        'update_columns': ['status'],
        'create': table(name='StintStatus')
    },
    'Stint':{
        'keys': ['SeasonID', 'GameID', 'TeamID', 'StintID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'StintID',
            'QtrStart',
            'QtrEnd',
            'ClockStart',
            'ClockEnd',
            'MinElapsedStart',
            'MinElapsedEnd',
            'MinutesPlayed',
            'Possessions',
            'PtsScored',
            'PtsAllowed',
            'FG2M',
            'FG2A',
            'FG3M',
            'FG3A',
            'FGM',
            'FGA',
            'FTM',
            'FTA',
            'OREB',
            'DREB',
            'REB',
            'AST',
            'TOV',
            'STL',
            'BLK',
            'BLKd',
            'F',
            'FDrwn'
        ],
        'update_columns': [
            'QtrEnd',
            'ClockEnd',
            'MinElapsedEnd',
            'MinutesPlayed',
            'Possessions',
            'PtsScored',
            'PtsAllowed',
            'FG2M',
            'FG2A',
            'FG3M',
            'FG3A',
            'FGM',
            'FGA',
            'FTM',
            'FTA',
            'OREB',
            'DREB',
            'REB',
            'AST',
            'TOV',
            'STL',
            'BLK',
            'BLKd',
            'F',
            'FDrwn'
        ],
        'check_query': '''
with TeamsOnCourt as(
select s.*
, dense_rank() over(partition by TeamID order by StintID desc) OnCourt
from Stint s
where s.SeasonID = season_id and s.GameID = game_id
)
select *
from TeamsOnCourt
where OnCourt = 1
order by OnCourt asc,TeamID''',
        'create': table(name='Stint')
    },
    'StintPlayer':{
        'keys': ['SeasonID', 'GameID', 'TeamID', 'StintID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'StintID',
            'PlayerID',
            'MinutesPlayed',
            'PlusMinus',
            'PTS',
            'AST',
            'REB',
            'FG2M',
            'FG2A',
            'FG3M',
            'FG3A',
            'FGM',
            'FGA',
            'FTM',
            'FTA',
            'OREB',
            'DREB',
            'TOV',
            'STL',
            'BLK',
            'BLKd',
            'F',
            'FDrwn'
        ],
        'update_columns': [
            'MinutesPlayed',
            'PlusMinus',
            'PTS',
            'AST',
            'REB',
            'FG2M',
            'FG2A',
            'FG3M',
            'FG3A',
            'FGM',
            'FGA',
            'FTM',
            'FTA',
            'OREB',
            'DREB',
            'TOV',
            'STL',
            'BLK',
            'BLKd',
            'F',
            'FDrwn'
        ],
        'check_query': '''
with PlayersOnCourt as(
select sp.*
, dense_rank() over(partition by TeamID order by StintID desc) OnCourt
from StintPlayer sp
where sp.SeasonID = season_id and sp.GameID = game_id
)
select *
from PlayersOnCourt
where OnCourt = 1
order by OnCourt asc,TeamID, PlayerID
''',
        'create': table(name='StintPlayer')
    },
    'Schedule': {
        'keys': ['SeasonID', 'GameID'],
        'columns': [
            'SeasonID',
            'GameID',
            'GameType',
            'Status',
            'Sequence',
            'GameTimeEST',
            'GameTimeUTC',
            'GameTimeHome',
            'GameTimeAway',
            'Day',
            'Week',
            'Label',
            'LabelDetail',
            'IsNeutral',
            'HomeID',
            'HomeWins',
            'HomeLosses',
            'HomeScore',
            'HomeSeed',
            'AwayID',
            'AwayWins',
            'AwayLosses',
            'AwayScore',
            'AwaySeed',
            'IfNecessary',
            'SeriesText',

        ],
        'update_columns':[
            'GameType',
            'Status',
            'Sequence',
            'GameTimeEST',
            'GameTimeUTC',
            'GameTimeHome',
            'GameTimeAway',
            'Day',
            'Week',
            'Label',
            'LabelDetail',
            'IsNeutral',
            'HomeID',
            'HomeWins',
            'HomeLosses',
            'HomeScore',
            'HomeSeed',
            'AwayID',
            'AwayWins',
            'AwayLosses',
            'AwayScore',
            'AwaySeed',
            'IfNecessary',
            'SeriesText',
        ],
        'check_query': '''
select s.SeasonID
, s.GameID
, s.Status
, s.HomeID
, h.Name HomeName
, h.City HomeCity
, h.Tricode HomeTri
, s.HomeWins
, s.HomeLosses
, s.HomeScore
, s.HomeSeed
, s.AwayID
, a.Name AwayName
, a.City AwayCity
, a.Tricode AwayTri
, s.AwayWins
, s.AwayLosses
, s.AwayScore
, s.AwaySeed
, s.IfNecessary
, s.SeriesText
from Schedule s
left join Team h on s.SeasonID = h.SeasonID and s.HomeID = h.TeamID
left join Team a on s.SeasonID = a.SeasonID and s.AwayID = a.TeamID
where s.SeasonID = season_id and s.GameID in(game_id)
''',
        'create': table(name='Schedule')
    },
    'DailyLineups': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID', 
            'GameID', 
            'TeamID', 
            'MatchupID', 
            'PlayerID', 
            'Position',
            'LineupStatus',
            'RosterStatus',
            'Timestamp'
        ],
        'update_columns': [
            'Position',
            'LineupStatus',
            'RosterStatus',
            'Timestamp'
        ],
        'create': table('DailyLineups')
    },
#endregion schema: dbo


#region Advanced Stats
    'adv.PlayerBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID','GameID', 'TeamID', 'MatchupID', 'PlayerID',
            'Minutes',
            'OffRTG',
            'DefRTG',
            'NetRTG',
            '[Ast%]',
            'ATR',
            'AstRatio',
            '[OReb%]',
            '[DReb%]',
            '[Reb%]',
            '[TeamTOV%]',
            '[EFG%]',
            '[TS%]',
            '[Usage%]',
            'Pace',
            'PacePer40',
            'PIE',
            'Possessions',
            'FGM',
            'FGA',
            '[FG%]',
        ],
        'update_columns': [
            'Minutes',
            'OffRTG',
            'DefRTG',
            'NetRTG',
            '[Ast%]',
            'ATR',
            'AstRatio',
            '[OReb%]',
            '[DReb%]',
            '[Reb%]',
            '[TeamTOV%]',
            '[EFG%]',
            '[TS%]',
            '[Usage%]',
            'Pace',
            'PacePer40',
            'PIE',
            'Possessions',
            'FGM',
            'FGA',
            '[FG%]',
        ],
        'create': table('adv.PlayerBox')
    },
    'adv.TeamBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'OffRTG',
            'DefRTG',
            'NetRTG',
            '[Ast%]',
            'ATR',
            'AstRatio',
            '[OReb%]',
            '[DReb%]',
            '[Reb%]',
            '[TeamTOV%]',
            'EOffRTG',
            'EDefRTG',
            'ENetRTG',
            '[EFG%]',
            '[TS%]',
            'Pace',
            'PacePer40',
            'PIE',
            'Possessions',
        ],
        'update_columns': [
            'OffRTG',
            'DefRTG',
            'NetRTG',
            '[Ast%]',
            'ATR',
            'AstRatio',
            '[OReb%]',
            '[DReb%]',
            '[Reb%]',
            '[TeamTOV%]',
            'EOffRTG',
            'EDefRTG',
            'ENetRTG',
            '[EFG%]',
            '[TS%]',
            'Pace',
            'PacePer40',
            'PIE',
            'Possessions',
        ],
        'create': table('adv.TeamBox')
    },
    'misc.PlayerBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID',
            'PtsTurnover',
            'PtsSecondChance',
            'PtsFastBreak',
            'PtsInThePaint',
            'OpPtsTurnover',
            'OpPtsSecondChance',
            'OpPtsFastBreak',
            'OpPtsInThePaint'
        ],
        'update_columns': [
            'PtsTurnover',
            'PtsSecondChance',
            'PtsFastBreak',
            'PtsInThePaint',
            'OpPtsTurnover',
            'OpPtsSecondChance',
            'OpPtsFastBreak',
            'OpPtsInThePaint'
        ],
        'create': table('misc.PlayerBox')
    },
    'misc.TeamBox': {
        'keys': [
			'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID'
		],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PtsTurnover',
            'PtsSecondChance',
            'PtsFastBreak',
            'PtsInThePaint',
            'OpPtsTurnover',
            'OpPtsSecondChance',
            'OpPtsFastBreak',
            'OpPtsInThePaint',
        ],
        'update_columns': [
            'PtsTurnover',
            'PtsSecondChance',
            'PtsFastBreak',
            'PtsInThePaint',
            'OpPtsTurnover',
            'OpPtsSecondChance',
            'OpPtsFastBreak',
            'OpPtsInThePaint',
        ],
        'create': table('misc.TeamBox')
	},
    'usage.PlayerBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID',
            '[Usage%]',
            '[%TeamFGM]',
            '[%TeamFGA]',
            '[%TeamFG3M]',
            '[%TeamFG3A]',
            '[%TeamFTM]',
            '[%TeamFTA]',
            '[%TeamOREB]',
            '[%TeamDREB]',
            '[%TeamREB]',
            '[%TeamAST]',
            '[%TeamTOV]',
            '[%TeamSTL]',
            '[%TeamBLK]',
            '[%TeamBLKd]',
            '[%TeamPF]',
            '[%TeamPFDrwn]',
            '[%TeamPTS]'

        ],
        'update_columns': [
            '[Usage%]',
            '[%TeamFGM]',
            '[%TeamFGA]',
            '[%TeamFG3M]',
            '[%TeamFG3A]',
            '[%TeamFTM]',
            '[%TeamFTA]',
            '[%TeamOREB]',
            '[%TeamDREB]',
            '[%TeamREB]',
            '[%TeamAST]',
            '[%TeamTOV]',
            '[%TeamSTL]',
            '[%TeamBLK]',
            '[%TeamBLKd]',
            '[%TeamPF]',
            '[%TeamPFDrwn]',
            '[%TeamPTS]'
        ],
        'create': table(name='usage.PlayerBox')
    },
    'ffactors.TeamBox': {
        'keys': [
			'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID'
		],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            '[EFG%]',
            'FTARate',
            '[TOV%]',
            '[OReb%]',
            '[OpEFG%]',
            'OpFTARate',
            '[OpTOV%]',
            '[OpOReb%]',
        ],
        'update_columns': [
            '[EFG%]',
            'FTARate',
            '[TOV%]',
            '[OReb%]',
            '[OpEFG%]',
            'OpFTARate',
            '[OpTOV%]',
            '[OpOReb%]',
        ],
        'create': table('ffactors.TeamBox')
	},
    'violations.PlayerBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID',
            'Travel',
            'DblDribble',
            'Inbound',
            'Backcourt',
            'Palming',
            'OffFoul',
            'Off3',
            'OffGoaltend',
            'Def3',
            'DefGoaltend',
            'Charge',
            'Lane',
            'JumpBall',
            'KickedBall',
            'DiscDribble',
        ],
        'update_columns': [
            'Travel',
            'DblDribble',
            'Inbound',
            'Backcourt',
            'Palming',
            'OffFoul',
            'Off3',
            'OffGoaltend',
            'Def3',
            'DefGoaltend',
            'Charge',
            'Lane',
            'JumpBall',
            'KickedBall',
            'DiscDribble',
        ],
        'create': table('violations.PlayerBox')
    },
    'violations.TeamBox': {
        'keys': [
			'SeasonID',
			'GameID',
			'TeamID',
			'MatchupID'
		],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'Travel',
            'DblDribble',
            'Inbound',
            'Backcourt',
            'Palming',
            'OffFoul',
            'Off3',
            'OffGoaltend',
            'Def3',
            'DefGoaltend',
            'FiveSec',
            'EightSec',
            'ShotClock',
            'Charge',
            'DelayOfGame',
            'Lane',
            'JumpBall',
            'KickedBall',
            'DiscDribble',
        ],
        'update_columns': [
            'Travel',
            'DblDribble',
            'Inbound',
            'Backcourt',
            'Palming',
            'OffFoul',
            'Off3',
            'OffGoaltend',
            'Def3',
            'DefGoaltend',
            'FiveSec',
            'EightSec',
            'ShotClock',
            'Charge',
            'DelayOfGame',
            'Lane',
            'JumpBall',
            'KickedBall',
            'DiscDribble',
        ],
        'create': table('violations.TeamBox')
    },
    'def.PlayerBox': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID',
            '[DReb%]',
            '[%TeamDReb]',
            '[%TeamSTL]',
            '[%TeamBLK]',
            'DefWinShare',
        ],
        'update_columns': [
            '[DReb%]',
            '[%TeamDReb]',
            '[%TeamSTL]',
            '[%TeamBLK]',
            'DefWinShare',
        ],
        'create': table('def.PlayerBox')
    },
    'def.TeamBox': {
        'keys': [
			'SeasonID',
			'GameID',
			'TeamID',
			'MatchupID'
		],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            '[DReb%]',
        ],
        'update_columns': [
            '[DReb%]',
        ],
        'create': table('def.TeamBox')
    },
    
#endregion Advanced Stats


#region schema: tracking
    'tracking.TeamDrives': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID',],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'Drives',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'PTS',
            '[PTS%]',
            'Passes',
            '[Pass%]',
            'AST',
            '[AST%]',
            'TOV',
            '[TOV%]',
            'PF',
            '[PF%]',
        ],
        'update_columns': [
            'Drives',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'PTS',
            '[PTS%]',
            'Passes',
            '[Pass%]',
            'AST',
            '[AST%]',
            'TOV',
            '[TOV%]',
            'PF',
            '[PF%]',
        ],
        'create': table('tracking.TeamDrives')
    },
    'tracking.PlayerDrives': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'Drives',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'PTS',
            '[PTS%]',
            'Passes',
            '[Pass%]',
            'AST',
            '[AST%]',
            'TOV',
            '[TOV%]',
            'PF',
            '[PF%]',
        ],
        'update_columns': [
            'Drives',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'PTS',
            '[PTS%]',
            'Passes',
            '[Pass%]',
            'AST',
            '[AST%]',
            'TOV',
            '[TOV%]',
            'PF',
            '[PF%]',
        ],
        'create': table('tracking.PlayerDrives')
    },
    'tracking.TeamPassing': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PassMade',
            'PassRcvd',
            'Ast',
            'AstFT',
            'AstSecondary',
            'AstPotential',
            'AstPointsCreated',
            'AstAdj',
            '[AstToPass%]',
            '[AstToPass%Adj]',
        ],
        'update_columns': [
            'PassMade',
            'PassRcvd',
            'Ast',
            'AstFT',
            'AstSecondary',
            'AstPotential',
            'AstPointsCreated',
            'AstAdj',
            '[AstToPass%]',
            '[AstToPass%Adj]',
        ],
        'create': table('tracking.TeamPassing')
    },
    'tracking.PlayerPassing': {
        'keys': ['SeasonID', 'GameID', 'TeamID', 'MatchupID', 'PlayerID'],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'PassMade',
            'PassRcvd',
            'Ast',
            'AstFT',
            'AstSecondary',
            'AstPotential',
            'AstPointsCreated',
            'AstAdj',
            '[AstToPass%]',
            '[AstToPass%Adj]',
        ],
        'update_columns': [
            'PassMade',
            'PassRcvd',
            'Ast',
            'AstFT',
            'AstSecondary',
            'AstPotential',
            'AstPointsCreated',
            'AstAdj',
            '[AstToPass%]',
            '[AstToPass%Adj]',
        ],
        'create': table('tracking.PlayerPassing')
    },
    'tracking.TeamDefense': {
        'keys': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'DefRimFGM',
            'DefRimFGA',
            '[DefRimFG%]',
        ],
        'update_columns': [
            'DefRimFGM',
            'DefRimFGA',
            '[DefRimFG%]',
        ],
        'create': table('tracking.TeamDefense')
    },
    'tracking.PlayerDefense': {
        'keys': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'DefRimFGM',
            'DefRimFGA',
            '[DefRimFG%]',
        ],
        'update_columns': [
            'DefRimFGM',
            'DefRimFGA',
            '[DefRimFG%]',
        ],
        'create': table('tracking.PlayerDefense')
    },
    'tracking.TeamCatchShoot': {
        'keys': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'update_columns': [
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'create': table('tracking.TeamCatchShoot')
    },
    'tracking.PlayerCatchShoot': {
        'keys': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'update_columns': [
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'create': table('tracking.PlayerCatchShoot')
    },
    'tracking.TeamPossessions': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'Pts',
            'Touches',
            'TouchFrontCourt',
            'PossTime',
            'SecPerTouch',
            'DribblePerTouch',
            'PtsPerTouch',
            'TouchElbow',
            'TouchPost',
            'TouchPaint',
            'PtsPerElbowTouch',
            'PtsPerPostTouch',
            'PtsPerPaintTouch',
        ],
        'update_columns': [
            'Pts',
            'Touches',
            'TouchFrontCourt',
            'PossTime',
            'SecPerTouch',
            'DribblePerTouch',
            'PtsPerTouch',
            'TouchElbow',
            'TouchPost',
            'TouchPaint',
            'PtsPerElbowTouch',
            'PtsPerPostTouch',
            'PtsPerPaintTouch',
        ],
        'create': table('tracking.TeamPossessions')
    },
    'tracking.PlayerPossessions': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'Pts',
            'Touches',
            'TouchFrontCourt',
            'PossTime',
            'SecPerTouch',
            'DribblePerTouch',
            'PtsPerTouch',
            'TouchElbow',
            'TouchPost',
            'TouchPaint',
            'PtsPerElbowTouch',
            'PtsPerPostTouch',
            'PtsPerPaintTouch',
        ],
        'update_columns': [
            'Pts',
            'Touches',
            'TouchFrontCourt',
            'PossTime',
            'SecPerTouch',
            'DribblePerTouch',
            'PtsPerTouch',
            'TouchElbow',
            'TouchPost',
            'TouchPaint',
            'PtsPerElbowTouch',
            'PtsPerPostTouch',
            'PtsPerPaintTouch',
        ],
        'create': table('tracking.PlayerPossessions')
    },
    'tracking.TeamPullUpShot': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'update_columns': [
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'create': table('tracking.TeamPullUpShot')
    },
    'tracking.PlayerPullUpShot': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'update_columns': [
            'FGM',
            'FGA',
            '[FG%]',
            'PTS',
            'FG3M',
            'FG3A',
            '[FG3%]',
            '[EFG%]',
        ],
        'create': table('tracking.PlayerPullUpShot')
    },
    
    'tracking.TeamRebounding': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'OReb',
            'ORebContested',
            'ORebUnContested',
            'ORebChances',
            'ORebChanceDefer',
            'AvgORebDist',
            'DReb',
            'DRebContested',
            'DRebUnContested',
            'DRebChances',
            'DRebChanceDefer',
            'AvgDRebDist',
            'Reb',
            'RebContested',
            'RebUnContested',
            'RebChances',
            'RebChanceDefer',
            'AvgRebDist',
            '[ORebContested%]',
            '[ORebChance%]',
            '[ORebChanceAdj%]',
            '[DRebContested%]',
            '[DRebChance%]',
            '[DRebChanceAdj%]',
            '[RebContested%]',
            '[RebChance%]',
            '[RebChanceAdj%]',
        ],
        'update_columns': [
            'OReb',
            'ORebContested',
            'ORebUnContested',
            'ORebChances',
            'ORebChanceDefer',
            'AvgORebDist',
            'DReb',
            'DRebContested',
            'DRebUnContested',
            'DRebChances',
            'DRebChanceDefer',
            'AvgDRebDist',
            'Reb',
            'RebContested',
            'RebUnContested',
            'RebChances',
            'RebChanceDefer',
            'AvgRebDist',
            '[ORebContested%]',
            '[ORebChance%]',
            '[ORebChanceAdj%]',
            '[DRebContested%]',
            '[DRebChance%]',
            '[DRebChanceAdj%]',
            '[RebContested%]',
            '[RebChance%]',
            '[RebChanceAdj%]',
        ],
        'create': table('tracking.TeamRebounding')
    },
    'tracking.PlayerRebounding': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'OReb',
            'ORebContested',
            'ORebUnContested',
            'ORebChances',
            'ORebChanceDefer',
            'AvgORebDist',
            'DReb',
            'DRebContested',
            'DRebUnContested',
            'DRebChances',
            'DRebChanceDefer',
            'AvgDRebDist',
            'Reb',
            'RebContested',
            'RebUnContested',
            'RebChances',
            'RebChanceDefer',
            'AvgRebDist',
            '[ORebContested%]',
            '[ORebChance%]',
            '[ORebChanceAdj%]',
            '[DRebContested%]',
            '[DRebChance%]',
            '[DRebChanceAdj%]',
            '[RebContested%]',
            '[RebChance%]',
            '[RebChanceAdj%]',
        ],
        'update_columns': [
            'OReb',
            'ORebContested',
            'ORebUnContested',
            'ORebChances',
            'ORebChanceDefer',
            'AvgORebDist',
            'DReb',
            'DRebContested',
            'DRebUnContested',
            'DRebChances',
            'DRebChanceDefer',
            'AvgDRebDist',
            'Reb',
            'RebContested',
            'RebUnContested',
            'RebChances',
            'RebChanceDefer',
            'AvgRebDist',
            '[ORebContested%]',
            '[ORebChance%]',
            '[ORebChanceAdj%]',
            '[DRebContested%]',
            '[DRebChance%]',
            '[DRebChanceAdj%]',
            '[RebContested%]',
            '[RebChance%]',
            '[RebChanceAdj%]',
        ],
        'create': table('tracking.PlayerRebounding')
    },    
    'tracking.TeamEfficiency': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'DrivePts',
            'CatchShootPts',
            'PullUpPts',
            'PaintTouchPts',
            'PostTouchPts',
            'ElbowTouchPts',
            '[DriveFG%]',
            '[CatchShootFG%]',
            '[PullUpFG%]',
            '[PaintTouchFG%]',
            '[PostTouchFG%]',
            '[ElbowTouchFG%]',
            '[EFG%]',
        ],
        'update_columns': [
            'DrivePts',
            'CatchShootPts',
            'PullUpPts',
            'PaintTouchPts',
            'PostTouchPts',
            'ElbowTouchPts',
            '[DriveFG%]',
            '[CatchShootFG%]',
            '[PullUpFG%]',
            '[PaintTouchFG%]',
            '[PostTouchFG%]',
            '[ElbowTouchFG%]',
            '[EFG%]',
        ],
        'create': table('tracking.TeamEfficiency')
    },
    'tracking.PlayerEfficiency': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'DrivePts',
            'CatchShootPts',
            'PullUpPts',
            'PaintTouchPts',
            'PostTouchPts',
            'ElbowTouchPts',
            '[DriveFG%]',
            '[CatchShootFG%]',
            '[PullUpFG%]',
            '[PaintTouchFG%]',
            '[PostTouchFG%]',
            '[ElbowTouchFG%]',
            '[EFG%]',
        ],
        'update_columns': [
            'DrivePts',
            'CatchShootPts',
            'PullUpPts',
            'PaintTouchPts',
            'PostTouchPts',
            'ElbowTouchPts',
            '[DriveFG%]',
            '[CatchShootFG%]',
            '[PullUpFG%]',
            '[PaintTouchFG%]',
            '[PostTouchFG%]',
            '[ElbowTouchFG%]',
            '[EFG%]',
        ],
        'create': table('tracking.PlayerEfficiency')
    },    
    'tracking.TeamSpeedDistance': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'DistFeet',
            'DistMiles',
            'DistMilesOff',
            'DistMilesDef',
            'AvgSpeed',
            'AvgSpeedOff',
            'AvgSpeedDef',
        ],
        'update_columns': [
            'DistFeet',
            'DistMiles',
            'DistMilesOff',
            'DistMilesDef',
            'AvgSpeed',
            'AvgSpeedOff',
            'AvgSpeedDef',
        ],
        'create': table('tracking.TeamSpeedDistance')
    },
    'tracking.PlayerSpeedDistance': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'DistFeet',
            'DistMiles',
            'DistMilesOff',
            'DistMilesDef',
            'AvgSpeed',
            'AvgSpeedOff',
            'AvgSpeedDef',
        ],
        'update_columns': [
            'DistFeet',
            'DistMiles',
            'DistMilesOff',
            'DistMilesDef',
            'AvgSpeed',
            'AvgSpeedOff',
            'AvgSpeedDef',
        ],
        'create': table('tracking.PlayerSpeedDistance')
    },    
    'tracking.TeamElbowTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'TotalTouches',
            'ElbowTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'ElbowTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.TeamElbowTouch')
    },
    'tracking.PlayerElbowTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'TotalTouches',
            'ElbowTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'ElbowTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.PlayerElbowTouch')
    },    
    'tracking.TeamPostTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'TotalTouches',
            'PostTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'PostTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.TeamPostTouch')
    },
    'tracking.PlayerPostTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'TotalTouches',
            'PostTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'PostTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.PlayerPostTouch')
    },    
    'tracking.TeamPaintTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'TotalTouches',
            'PaintTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'PaintTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.TeamPaintTouch')
    },
    'tracking.PlayerPaintTouch': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'TotalTouches',
            'PaintTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'update_columns': [
            'TotalTouches',
            'PaintTouches',
            'FGM',
            'FGA',
            '[FG%]',
            'FTM',
            'FTA',
            '[FT%]',
            'Pts',
            'Passes',
            'Ast',
            'TOV',
            'Fouls',
            '[%ofPts]',
            '[Pass%]',
            '[Ast%]',
            '[TOV%]',
            '[Foul%]',
        ],
        'create': table('tracking.PlayerPaintTouch')
    },
    'tracking.TeamHustle': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'ContestedShots',
            'ContestedFG2',
            'ContestedFG3',
            'Deflections',
            'ChargesDrawn',
            'ScreenAst',
            'ScreenAstPts',
            'OffLooseBallsRec',
            'DefLooseBallsRec',
            'LooseBallsRec',
            'OffBoxouts',
            'DefBoxouts',
            'Boxouts',
            '[LooseBallsRecOff%]',
            '[LooseBallsRecDef%]',
            '[OffBoxout%]',
            '[DefBoxout%]',
        ],
        'update_columns': [
            'ContestedShots',
            'ContestedFG2',
            'ContestedFG3',
            'Deflections',
            'ChargesDrawn',
            'ScreenAst',
            'ScreenAstPts',
            'OffLooseBallsRec',
            'DefLooseBallsRec',
            'LooseBallsRec',
            'OffBoxouts',
            'DefBoxouts',
            'Boxouts',
            '[LooseBallsRecOff%]',
            '[LooseBallsRecDef%]',
            '[OffBoxout%]',
            '[DefBoxout%]',
        ],
        'create': table('tracking.TeamHustle')
    },
    'tracking.PlayerHustle': {
        'keys': [
          'SeasonID',
          'GameID',
          'TeamID',
          'MatchupID',
          'PlayerID'
        ],
        'columns': [
            'SeasonID',
            'GameID',
            'TeamID',
            'MatchupID',
            'PlayerID',
            'ContestedShots',
            'ContestedFG2',
            'ContestedFG3',
            'Deflections',
            'ChargesDrawn',
            'ScreenAst',
            'ScreenAstPts',
            'OffLooseBallsRec',
            'DefLooseBallsRec',
            'LooseBallsRec',
            'OffBoxouts',
            'DefBoxouts',
            'Boxouts',
            'BoxoutTeamReb',
            'BoxoutPersReb',
            '[LooseBallsRecOff%]',
            '[LooseBallsRecDef%]',
            '[OffBoxout%]',
            '[DefBoxout%]',
            '[BoxoutTeamReb%]',
            '[BoxoutPersReb%]',
        ],
        'update_columns': [
            'ContestedShots',
            'ContestedFG2',
            'ContestedFG3',
            'Deflections',
            'ChargesDrawn',
            'ScreenAst',
            'ScreenAstPts',
            'OffLooseBallsRec',
            'DefLooseBallsRec',
            'LooseBallsRec',
            'OffBoxouts',
            'DefBoxouts',
            'Boxouts',
            'BoxoutTeamReb',
            'BoxoutPersReb',
            '[LooseBallsRecOff%]',
            '[LooseBallsRecDef%]',
            '[OffBoxout%]',
            '[DefBoxout%]',
            '[BoxoutTeamReb%]',
            '[BoxoutPersReb%]',
        ],
        'create': table('tracking.PlayerHustle')
    },    
#endregion schema: tracking


#region schema: plays
    'plays.TeamPlays': {
        'keys': [
          'SeasonID',
          'TeamID',
          'Play',
          'Type',
          'GP',
        ],
        'columns': [
            'SeasonID',
            'TeamID',
            'Play',
            'Type',
            'GP',
            'Possessions',
            'Frequency',
            'PtsPerPoss',
            'FGM',
            'FGA',
            'PTS',
            '[FG%]',
            '[EFG%]',
            'FTFreq',
            'TOVFreq',
            'FDrwnFreq',
            'And1Freq',
            'ScoreFreq',
            'FGMX',
            'Percentile',
            'FirstDate',
            'LastDate',
        ],
        'update_columns': [
            'Possessions',
            'Frequency',
            'PtsPerPoss',
            'FGM',
            'FGA',
            'PTS',
            '[FG%]',
            '[EFG%]',
            'FTFreq',
            'TOVFreq',
            'FDrwnFreq',
            'And1Freq',
            'ScoreFreq',
            'FGMX',
            'Percentile',
            'LastDate',
        ],
        'create': table('plays.TeamPlays')
    },
    'plays.PlayerPlays': {
        'keys': [
          'SeasonID',
          'TeamID',
          'PlayerID',
          'Play',
          'Type',
          'GP',
        ],
        'columns': [
            'SeasonID',
            'TeamID',
            'PlayerID',
            'Play',
            'Type',
            'GP',
            'Possessions',
            'Frequency',
            'PtsPerPoss',
            'FGM',
            'FGA',
            'PTS',
            '[FG%]',
            '[EFG%]',
            'FTFreq',
            'TOVFreq',
            'FDrwnFreq',
            'And1Freq',
            'ScoreFreq',
            'FGMX',
            'Percentile',
            'FirstDate',
            'LastDate',
        ],
        'update_columns': [
            'Possessions',
            'Frequency',
            'PtsPerPoss',
            'FGM',
            'FGA',
            'PTS',
            '[FG%]',
            '[EFG%]',
            'FTFreq',
            'TOVFreq',
            'FDrwnFreq',
            'And1Freq',
            'ScoreFreq',
            'FGMX',
            'Percentile',
            'LastDate',
        ],
        'create': table('plays.PlayerPlays')
    },

#endregion schema: plays


    # 'plays.Team': {
    #     'keys': [
    #       'SeasonID',
    #       'TeamID',
    #       'Type',
    #       'GP',
    #     ],
    #     'columns': [

    #     ],
    #     'update_columns': [

    #     ],
    #     'create': table('plays.Team')
    # },
    # 'plays.Player': {
    #     'keys': [
    #       'SeasonID',
    #       'TeamID',
    #       'PlayerID',
    #       'Type',
    #       'GP',
    #     ],
    #     'columns': [

    #     ],
    #     'update_columns': [

    #     ],
    #     'create': table('plays.Player')
    # },

    

    
    # 'tracking.Team': {
    #     'keys': [
    #       'SeasonID',
    #       'GameID',
    #       'TeamID',
    #       'MatchupID'
    #     ],
    #     'columns': [

    #     ],
    #     'update_columns': [

    #     ],
    #     'create': table('tracking.Team')
    # },
    # 'tracking.Player': {
    #     'keys': [
    #       'SeasonID',
    #       'GameID',
    #       'TeamID',
    #       'MatchupID',
    #       'PlayerID'
    #     ],
    #     'columns': [

    #     ],
    #     'update_columns': [

    #     ],
    #     'create': table('tracking.Player')
    # },
}